declare const _default: {
    ENTRY_FORMAT_URL: string;
    STEP_URL: string;
    MAX_VALUE_URL: string;
    MIN_VALUE_URL: string;
    MIN_LENGTH_URL: string;
    MAX_OCCURS_URL: string;
    MIN_OCCURS_URL: string;
    REGEX_URL: string;
    ITEMCONTROL_URL: string;
    QUESTIONNAIRE_UNIT: string;
    MARKDOWN_URL: string;
    QUESTIONNAIRE_HIDDEN: string;
    ORDINAL_VALUE: string;
    VALIDATIONTEXT_URL: string;
    REPEATSTEXT_URL: string;
    OPTION_REFERENCE: string;
    CALCULATED_EXPRESSION: string;
    Copy_EXPRESSION: string;
    DATE_MAX_VALUE_URL: string;
    DATE_MIN_VALUE_URL: string;
    GUIDANCE_PARAMETER: string;
    GUIDANCE_ACTION: string;
    PRESENTATION_BUTTONS: string;
    NAVIGATOR: string;
    SUBLABEL: string;
    HYPERLINK: string;
};
export default _default;
