import { QuestionnaireItem, Extension, Element, Questionnaire, Coding } from '../types/fhir';
import { SidebarItem } from '../types/sidebar';
import { PresentationButtonsType } from '../constants/presentationButtonsType';
export declare function getValidationTextExtension(item: QuestionnaireItem): string | undefined;
export declare function getPresentationButtonsExtension(questionniare: Questionnaire): PresentationButtonsType | null;
export declare function getNavigatorExtension(questionniare: Questionnaire): Array<Coding> | undefined;
export declare function getSidebarSections(questionniare: Questionnaire, onRenderMarkdown?: (item: QuestionnaireItem, markup: string) => string): Array<SidebarItem>;
export declare function isItemSidebar(item: QuestionnaireItem): boolean;
export declare function getExtension(url: string, item: QuestionnaireItem | Element | Questionnaire): Extension | undefined;
export declare function getPlaceholder(item: QuestionnaireItem): string | undefined;
export declare function getQuestionnaireUnitExtensionValue(item: QuestionnaireItem): Coding | undefined;
export declare function getMaxValueExtensionValue(item: QuestionnaireItem): number | undefined;
export declare function getMinValueExtensionValue(item: QuestionnaireItem): number | undefined;
export declare function getMinOccursExtensionValue(item: QuestionnaireItem): number | undefined;
export declare function getMaxOccursExtensionValue(item: QuestionnaireItem): number | undefined;
export declare function getMinLengthExtensionValue(item: QuestionnaireItem): number | undefined;
export declare function getRegexExtension(item: QuestionnaireItem): string | undefined;
export declare function getRepeatsTextExtension(item: QuestionnaireItem): string | undefined;
export declare function getItemControlExtensionValue(item: QuestionnaireItem): Coding[] | undefined;
export declare function getMarkdownExtensionValue(item: QuestionnaireItem | Element): string | undefined;
export declare function getSublabelExtensionValue(item: QuestionnaireItem | Element): string | undefined;
export declare function getQuestionnaireHiddenExtensionValue(item: QuestionnaireItem): boolean | undefined;
export declare function getCalculatedExpressionExtension(item: QuestionnaireItem): Extension | undefined;
export declare function getCopyExtension(item: QuestionnaireItem): Extension | undefined;
export declare function getHyperlinkExtensionValue(item: QuestionnaireItem | Element | Questionnaire): number | undefined;
